---
language: python
python:
  - 3.6

services: docker

addons:
  apt:
    update: true

install:
  - docker build -f docker/dockerfile -t pyslackers/sirbot-pyslackers:$TRAVIS_COMMIT -t pyslackers/sirbot-pyslackers:latest .

script:
  - docker run --entrypoint scripts/test.sh pyslackers/sirbot-pyslackers:$TRAVIS_COMMIT

deploy:
    - provider: script
      script: scripts/docker_push.sh
      on:
        branch: master
        tags: false
        repo: pyslackers/sirbot-pyslackers
    - provider: script
      script: scripts/deploy.sh
      on:
        branch: master
        tags: false
        repo: pyslackers/sirbot-pyslackers
